# Generated by Django 5.2.5 on 2025-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSphere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isOrganizer',
            field=models.BooleanField(default=False),
        ),
    ]
