# Generated by Django 5.2.5 on 2025-09-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSphere', '0003_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='about',
        ),
        migrations.AddField(
            model_name='event',
            name='Img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
