# Generated by Django 5.2.5 on 2025-09-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventSphere', '0004_rename_description_event_about_event_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_str',
        ),
    ]
