# Generated by Django 5.2.5 on 2025-09-05 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSphere', '0005_rename_date_event_date_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_str',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
