# Generated by Django 5.2.5 on 2025-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSphere', '0009_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isCultural',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isSports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isTech',
            field=models.BooleanField(default=False),
        ),
    ]
