# Generated by Django 5.2.5 on 2025-09-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventSphere', '0010_event_iscultural_event_issports_event_istech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='isCultural',
        ),
        migrations.RemoveField(
            model_name='event',
            name='isSports',
        ),
        migrations.RemoveField(
            model_name='event',
            name='isTech',
        ),
    ]
